#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target=CI

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> recipe.cake, .config/dotnet-tools.json

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /(doc).*/
