//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Discord")]
[assembly: AssemblyDescription("Cake Discord AddIn")]
[assembly: AssemblyCompany("Cake Contributions")]
[assembly: AssemblyProduct("Cake.Discord")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright © Cake Contributions 2018 - Present")]
[assembly: CLSCompliant(true)]
