name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-22.04

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v2

        - name: Fetch all tags and branches
          run: git fetch --prune --unshallow

        - name: Cache Tools
          uses: actions/cache@v2
          with:
            path: tools
            key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake', '.config/dotnet-tools.json') }}

        # install libgit2-dev on ubuntu, so libgit2sharp works
        - name: Install libgit-dev
          if: runner.os == 'Linux'
          run: sudo apt-get install -y libgit2-dev

        - name: Setup required dotnet versions
          uses: actions/setup-dotnet@v4.0.1
          with:
            dotnet-version: |
              2.1.818
              3.1.x
              5.0.x
              6.0.x
              7.0.x
              8.0.x

        - name: Publishing documentaiton
          uses: cake-build/cake-action@v2.0.0
          with:
            script-path: recipe.cake
            target: Force-Publish-Documentation
            verbosity: Normal
            cake-version: tool-manifest