name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-22.04

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v2

        - name: Cache Tools
          uses: actions/cache@v2
          with:
            path: tools
            key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake', '.config/dotnet-tools.json') }}

        - name: Publishing documentaiton
          uses: cake-build/cake-action@v2.0.0
          with:
            script-path: recipe.cake
            target: Force-Publish-Documentation
            verbosity: Normal
            cake-version: tool-manifest